### ISSUE TITLE
Modifiable bin limits

### ISSUE THREAD

**Issue by jjocemac** [cemac-tech/LivingLabDataApp#11]
Would be good to have a separate text file containing the particle count bin limits that the python script then reads in to generate the colour bar. This would make it easier for us to change the bin limits in future (i.e. no Python experience necessary)

**Comment by nicktblr** [comment]
Note: the ability to make more bins has to come after we make a red-green colormap (issue #13) or remove it

**Comment by jjocemac** [comment]
Done in PR#24
