### ISSUE TITLE
Error reading in 'cubed' symbol in CPC file

### ISSUE THREAD

**Issue by jjocemac** [cemac-tech/LivingLabDataApp#4]
It is currently necessary to remove the 'cubed' symbol from the CPC files before uploading, or the site crashes

**Comment by nicktblr** [comment]
This should be fixed by changing it from UTF-8 to ISO-???

**Comment by jjocemac** [comment]
You could check this by trying to upload a 'cubed' CPC file, and close the issue if it is fixed.

**Comment by nicktblr** [comment]
Confirmed fixed.
Found the file encoding of the CSV files from the CPC (in file properties) and changed the encoding from UTF-8 (which doesn't accept special characters) to ISO-8859 15.

https://www.fileformat.info/info/charset/ISO-8859-15/list.htm
